services:
  - type: web
    name: autovid-api
    runtime: python
    plan: free

    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11

      - key: BASE_URL
        value: https://autovid-backend-1.onrender.com

      - key: MONGO_URL
        sync: false

      - key: DATABASE_NAME
        value: autovid_db

      - key: SECRET_KEY
        generateValue: true

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
